In [4]:
import pandas as pd
import glob
import os

In [5]:
# set search path and find all csv files
path = 'Resources'
all_files = glob.glob(path + "/*.csv")

In [6]:
# create empty list to store dataframes
li = []

for f in all_files:
    #read in csv
    df_raw = pd.read_csv(f, index_col=None)
    df_raw['filename'] = os.path.basename(f)
    li.append(df_raw)

df = pd.concat(li,axis=0,ignore_index=True)
print(df.shape)
df.head()

(404947, 16)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,filename
0,201,2019-01-01 03:09:09.7110,2019-01-01 03:12:30.8790,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29612,Subscriber,1993,1,JC-201901-citibike-tripdata.csv
1,505,2019-01-01 05:18:00.1060,2019-01-01 05:26:25.9050,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29213,Subscriber,1972,2,JC-201901-citibike-tripdata.csv
2,756,2019-01-01 10:36:33.3400,2019-01-01 10:49:10.2600,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26164,Subscriber,1985,1,JC-201901-citibike-tripdata.csv
3,1575,2019-01-01 12:43:38.6430,2019-01-01 13:09:54.5280,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29672,Customer,1969,0,JC-201901-citibike-tripdata.csv
4,1566,2019-01-01 12:43:39.6010,2019-01-01 13:09:46.5100,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29522,Customer,1969,0,JC-201901-citibike-tripdata.csv

In [7]:
df.count()

tripduration               404947
starttime                  404947
stoptime                   404947
start station id           404947
start station name         404947
start station latitude     404947
start station longitude    404947
end station id             404947
end station name           404947
end station latitude       404947
end station longitude      404947
bikeid                     404947
usertype                   404947
birth year                 404947
gender                     404947
filename                   404947
dtype: int64

In [8]:
# drop rows with NAN data
df = df.dropna()
df.count()

tripduration               404947
starttime                  404947
stoptime                   404947
start station id           404947
start station name         404947
start station latitude     404947
start station longitude    404947
end station id             404947
end station name           404947
end station latitude       404947
end station longitude      404947
bikeid                     404947
usertype                   404947
birth year                 404947
gender                     404947
filename                   404947
dtype: int64

In [9]:
# filter out trips under 3600 seconds
df.loc[df['tripduration']>3600]

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,filename
113,13030,2019-01-04 12:51:42.5750,2019-01-04 16:28:52.6280,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,29448,Subscriber,1969,0,JC-201901-citibike-tripdata.csv
835,69794,2019-01-03 04:32:56.5420,2019-01-03 23:56:10.9930,3184,Paulus Hook,40.714145,-74.033552,3184,Paulus Hook,40.714145,-74.033552,26202,Subscriber,1998,1,JC-201901-citibike-tripdata.csv
991,50228,2019-01-14 18:55:47.2800,2019-01-15 08:52:55.8090,3184,Paulus Hook,40.714145,-74.033552,3639,Harborside,40.719252,-74.034234,26227,Subscriber,1982,2,JC-201901-citibike-tripdata.csv
1627,33808,2019-01-28 08:56:40.3080,2019-01-28 18:20:08.4530,3185,City Hall,40.717732,-74.043845,3185,City Hall,40.717732,-74.043845,26232,Subscriber,1988,2,JC-201901-citibike-tripdata.csv
2415,3813,2019-01-09 11:18:12.0090,2019-01-09 12:21:45.2710,3186,Grove St PATH,40.719586,-74.043117,3275,Columbus Drive,40.718355,-74.038914,29616,Subscriber,1979,1,JC-201901-citibike-tripdata.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404557,4248,2019-12-31 13:03:40.3130,2019-12-31 14:14:28.9690,3205,JC Medical Center,40.716540,-74.049638,3205,JC Medical Center,40.716540,-74.049638,29515,Customer,1969,0,JC-201912-citibike-tripdata.csv
404570,3693,2019-12-31 13:12:55.2470,2019-12-31 14:14:28.8760,3205,JC Medical Center,40.716540,-74.049638,3205,JC Medical Center,40.716540,-74.049638,26238,Customer,1969,0,JC-201912-citibike-tripdata.csv
404724,3921,2019-12-31 15:49:12.0230,2019-12-31 16:54:33.1140,3268,Lafayette Park,40.713464,-74.062859,3268,Lafayette Park,40.713464,-74.062859,29449,Customer,1969,0,JC-201912-citibike-tripdata.csv
404940,4723,2019-12-31 22:58:42.2410,2020-01-01 00:17:25.7980,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3192,Liberty Light Rail,40.711242,-74.055701,29544,Customer,1969,0,JC-201912-citibike-tripdata.csv
404941,5008,2019-12-31 22:58:52.8870,2020-01-01 00:22:21.1070,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3268,Lafayette Park,40.713464,-74.062859,29280,Customer,1969,0,JC-201912-citibike-tripdata.csv

In [ ]:
#df['tripduration'] = pd.to_datetime(df['tripduration'], unit='s')

In [10]:
# calculate age of riders
ages = []

for i in df["birth year"]:
    age = 2019 - i
    ages.append(age)

df["age"] = ages
df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,filename,age
0,201,2019-01-01 03:09:09.7110,2019-01-01 03:12:30.8790,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29612,Subscriber,1993,1,JC-201901-citibike-tripdata.csv,26
1,505,2019-01-01 05:18:00.1060,2019-01-01 05:26:25.9050,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29213,Subscriber,1972,2,JC-201901-citibike-tripdata.csv,47
2,756,2019-01-01 10:36:33.3400,2019-01-01 10:49:10.2600,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26164,Subscriber,1985,1,JC-201901-citibike-tripdata.csv,34
3,1575,2019-01-01 12:43:38.6430,2019-01-01 13:09:54.5280,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29672,Customer,1969,0,JC-201901-citibike-tripdata.csv,50
4,1566,2019-01-01 12:43:39.6010,2019-01-01 13:09:46.5100,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29522,Customer,1969,0,JC-201901-citibike-tripdata.csv,50

In [11]:
df.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id             int64
start station name          object
start station latitude     float64
start station longitude    float64
end station id               int64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
usertype                    object
birth year                   int64
gender                       int64
filename                    object
age                          int64
dtype: object

In [12]:
# save dataset as csv
df.to_csv("Resources/2019_tripdata_JC.csv", index=False)