In [1]:
import pandas as pd
import glob
import os

In [2]:
# set search path and find all csv files
path = 'Resources'
all_files = glob.glob(path + "/*.csv")

In [3]:
# create empty list to store dataframes
li = []

for f in all_files:
    #read in csv
    df_raw = pd.read_csv(f, index_col=None)
    df_raw['filename'] = os.path.basename(f)
    li.append(df_raw)

df = pd.concat(li,axis=0,ignore_index=True)
print(df.shape)
df.head()

(833238, 16)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,filename
0,410,2017-10-01 00:03:08,2017-10-01 00:09:59,3213,Van Vorst Park,40.718489,-74.047727,3192,Liberty Light Rail,40.711242,-74.055701,26187,Subscriber,1976.0,1,JC-201710-citibike-tripdata.csv
1,412,2017-10-01 00:03:13,2017-10-01 00:10:06,3213,Van Vorst Park,40.718489,-74.047727,3192,Liberty Light Rail,40.711242,-74.055701,31768,Subscriber,1975.0,2,JC-201710-citibike-tripdata.csv
2,274,2017-10-01 00:24:07,2017-10-01 00:28:42,3195,Sip Ave,40.730743,-74.063784,3194,McGinley Square,40.725340,-74.067622,26311,Subscriber,1979.0,1,JC-201710-citibike-tripdata.csv
3,2198,2017-10-01 00:31:03,2017-10-01 01:07:42,3199,Newport Pkwy,40.728745,-74.032108,3183,Exchange Place,40.716247,-74.033459,31709,Subscriber,1994.0,1,JC-201710-citibike-tripdata.csv
4,166,2017-10-01 00:34:09,2017-10-01 00:36:56,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,31759,Subscriber,1967.0,2,JC-201710-citibike-tripdata.csv

In [4]:
df.count()

tripduration               833238
starttime                  833238
stoptime                   833238
start station id           833238
start station name         833238
start station latitude     833238
start station longitude    833238
end station id             833238
end station name           833238
end station latitude       833238
end station longitude      833238
bikeid                     833238
usertype                   833238
birth year                 829783
gender                     833238
filename                   833238
dtype: int64

In [5]:
# drop rows with NAN data
df = df.dropna()
df.count()

tripduration               829783
starttime                  829783
stoptime                   829783
start station id           829783
start station name         829783
start station latitude     829783
start station longitude    829783
end station id             829783
end station name           829783
end station latitude       829783
end station longitude      829783
bikeid                     829783
usertype                   829783
birth year                 829783
gender                     829783
filename                   829783
dtype: int64

In [7]:
# filter out trips under 3600 seconds
df.loc[df['tripduration']>3600]

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,filename
44,5303,2017-10-01 07:18:29,2017-10-01 08:46:52,3275,Columbus Drive,40.718355,-74.038914,3275,Columbus Drive,40.718355,-74.038914,31803,Subscriber,1985.0,1,JC-201710-citibike-tripdata.csv
74,12967,2017-10-01 08:39:56,2017-10-01 12:16:03,3211,Newark Ave,40.721525,-74.046305,3267,Morris Canal,40.712419,-74.038526,31920,Subscriber,1981.0,2,JC-201710-citibike-tripdata.csv
97,5375,2017-10-01 09:14:29,2017-10-01 10:44:04,3192,Liberty Light Rail,40.711242,-74.055701,3192,Liberty Light Rail,40.711242,-74.055701,31347,Subscriber,1978.0,1,JC-201710-citibike-tripdata.csv
152,4846,2017-10-01 10:35:54,2017-10-01 11:56:40,3186,Grove St PATH,40.719586,-74.043117,3186,Grove St PATH,40.719586,-74.043117,31698,Subscriber,1985.0,1,JC-201710-citibike-tripdata.csv
222,8903,2017-10-01 11:40:34,2017-10-01 14:08:58,3203,Hamilton Park,40.727596,-74.044247,3203,Hamilton Park,40.727596,-74.044247,26168,Subscriber,1965.0,1,JC-201710-citibike-tripdata.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
832848,4248,2019-12-31 13:03:40.3130,2019-12-31 14:14:28.9690,3205,JC Medical Center,40.716540,-74.049638,3205,JC Medical Center,40.716540,-74.049638,29515,Customer,1969.0,0,JC-201912-citibike-tripdata.csv
832861,3693,2019-12-31 13:12:55.2470,2019-12-31 14:14:28.8760,3205,JC Medical Center,40.716540,-74.049638,3205,JC Medical Center,40.716540,-74.049638,26238,Customer,1969.0,0,JC-201912-citibike-tripdata.csv
833015,3921,2019-12-31 15:49:12.0230,2019-12-31 16:54:33.1140,3268,Lafayette Park,40.713464,-74.062859,3268,Lafayette Park,40.713464,-74.062859,29449,Customer,1969.0,0,JC-201912-citibike-tripdata.csv
833231,4723,2019-12-31 22:58:42.2410,2020-01-01 00:17:25.7980,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3192,Liberty Light Rail,40.711242,-74.055701,29544,Customer,1969.0,0,JC-201912-citibike-tripdata.csv
833232,5008,2019-12-31 22:58:52.8870,2020-01-01 00:22:21.1070,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3268,Lafayette Park,40.713464,-74.062859,29280,Customer,1969.0,0,JC-201912-citibike-tripdata.csv

In [9]:
df['tripduration'] = pd.to_datetime(df['tripduration'], unit='s')
df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,filename
0,1970-01-01 00:06:50,2017-10-01 00:03:08,2017-10-01 00:09:59,3213,Van Vorst Park,40.718489,-74.047727,3192,Liberty Light Rail,40.711242,-74.055701,26187,Subscriber,1976.0,1,JC-201710-citibike-tripdata.csv
1,1970-01-01 00:06:52,2017-10-01 00:03:13,2017-10-01 00:10:06,3213,Van Vorst Park,40.718489,-74.047727,3192,Liberty Light Rail,40.711242,-74.055701,31768,Subscriber,1975.0,2,JC-201710-citibike-tripdata.csv
2,1970-01-01 00:04:34,2017-10-01 00:24:07,2017-10-01 00:28:42,3195,Sip Ave,40.730743,-74.063784,3194,McGinley Square,40.725340,-74.067622,26311,Subscriber,1979.0,1,JC-201710-citibike-tripdata.csv
3,1970-01-01 00:36:38,2017-10-01 00:31:03,2017-10-01 01:07:42,3199,Newport Pkwy,40.728745,-74.032108,3183,Exchange Place,40.716247,-74.033459,31709,Subscriber,1994.0,1,JC-201710-citibike-tripdata.csv
4,1970-01-01 00:02:46,2017-10-01 00:34:09,2017-10-01 00:36:56,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,31759,Subscriber,1967.0,2,JC-201710-citibike-tripdata.csv

In [14]:
df.dtypes

tripduration               datetime64[ns]
starttime                          object
stoptime                           object
start station id                    int64
start station name                 object
start station latitude            float64
start station longitude           float64
end station id                      int64
end station name                   object
end station latitude              float64
end station longitude             float64
bikeid                              int64
usertype                           object
birth year                        float64
gender                              int64
filename                           object
startdate                          object
start_time                         object
stopdate                           object
stop_time                          object
year                                int64
dtype: object

In [16]:
# save dataset as csv
df.to_csv("Resources/2017_2018_tripdata_JC")